### ISSUE TITLE
Security improvements

### ISSUE THREAD

**Issue by yuriy77k** [yuriy77k/CallistoBridge#1]
1. Allow owner to withdraw tokens that were transferred to contract by mistake (was not deposited by `deposit` function).
2. `Owner` can use `onlyOwners` functions in 24h after enabling `setup mode`
3. `Owner` can update contract only in `setup mode`
4. `Owner` can use the function `removeAuthority` once per 24h without switching into `setup mode`

**Comment by Dexaran** [comment]
5. `Owner` can replace one of the "founders" in `founders multisig` once per 72 hours
